from app.models import db, User, environment, SCHEMA
from sqlalchemy.sql import text
import random


# Adds a demo user, you can add other users here if you want
def seed_users():
    valid_cities = ["New York", "Los Angeles", "London", "Tokyo", "Paris", "Sydney", "Toronto", "Berlin"]
    valid_countries = ["United States", "United Kingdom", "Japan", "France", "Australia", "Canada", "Germany"]

# Create a list of user data objects
    user_data = [
        {
            "username": "Demo",
            "email": "demo@aa.io",
            "password": "password",
            "first_name": "Demo",
            "last_name": "FiftyNine",
            "display_name": "DisplayName",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "This is a demo account for demo users",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "marnie",
            "email": "marnie@aa.io",
            "password": "password",
            "first_name": "Marnie",
            "last_name": "Simpson",
            "display_name": "DisplayName",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Fill in your bio",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "bobbie",
            "email": "bobbie@aa.io",
            "password": "password",
            "first_name": "Bobbie",
            "last_name": "Chocomaria",
            "display_name": "DisplayName",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Fill something here for your bio",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "barnie",
            "email": "barnie@aa.io",
            "password": "password",
            "first_name": "Barnie",
            "last_name": "Samsung",
            "display_name": "DisplayName",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Fill in your bio here",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "minh",
            "email": "minh@aa.io",
            "password": "password",
            "first_name": "BangerSounds",
            "last_name": "CEO",
            "display_name": "DisplayName",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Im gaming right now brb",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "chris",
            "email": "chris@aa.io",
            "password": "password",
            "first_name": "Chris",
            "last_name": "Thornburg",
            "display_name": "DisplayName",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Rick roll og",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "jenny",
            "email": "jenny@aa.io",
            "password": "password",
            "first_name": "Jenny",
            "last_name": "Lee",
            "display_name": "DisplayName",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "I like to go for marathonicaltacular runs",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "casey",
            "email": "casey@aa.io",
            "password": "password",
            "first_name": "Casey",
            "last_name": "O'neil",
            "display_name": "DisplayName",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Just some random grid user",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "seabass",
            "email": "seabass@aa.io",
            "password": "password",
            "first_name": "Seabass",
            "last_name": "Stovall",
            "display_name": "DisplayName",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Bottoms up!!!!",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "nate",
            "email": "nate@aa.io",
            "password": "password",
            "first_name": "Nate",
            "last_name": "B",
            "display_name": "DisplayName",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "I like going on dates.",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "james",
            "email": "james@aa.io",
            "password": "password",
            "first_name": "James",
            "last_name": "NotTheAsianOne",
            "display_name": "DisplayName",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "I used to be depressed, I still am, but I used to be too.",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "cartman",
            "email": "cartman@aa.io",
            "password": "password",
            "first_name": "eric theodore",
            "last_name": "cartman",
            "display_name": "CartmanChangingTheRapGame",
            "profile_image": "https://cdn.discordapp.com/attachments/1108904522220318781/1142128184867946576/cartman.JPG",
            "profile_bio": "I used to be depressed, I still am, but I used to be too.",
            "profile_city": "South Park",
            "profile_country": "United States",
            "profile_background": "https://c4.wallpaperflare.com/wallpaper/758/235/652/south-park-eric-cartman-wallpaper-preview.jpg",
        },
        {
            "username": "SLANDER",
            "email": "slander@aa.io",
            "password": "password",
            "first_name": "Derek",
            "last_name": "Anderson",  # Made-up last name
            "display_name": "SLANDER",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Bass music producers",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "XXXTENTACION",
            "email": "xxxtentacion@aa.io",
            "password": "password",
            "first_name": "Jahseh",
            "last_name": "Onfroy",
            "display_name": "XXXTENTACION",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Rapper and songwriter",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "1nonly",
            "email": "1nonly@aa.io",
            "password": "password",
            "first_name": "One",
            "last_name": "AndOnly",
            "display_name": "1nonly",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Music producer",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "NateTraveler",
            "email": "natetraveler@aa.io",
            "password": "password",
            "first_name": "Nate",
            "last_name": "Traveler",
            "display_name": "Nate Traveler",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Exploring the world through music",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "eaJ",
            "email": "eaj@aa.io",
            "password": "password",
            "first_name": "Jae",
            "last_name": "Park",
            "display_name": "eaJ",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Musician and producer",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "LinkinPark",
            "email": "linkinpark@aa.io",
            "password": "password",
            "first_name": "Chester",
            "last_name": "Bennington",  # Made-up last name
            "display_name": "Linkin Park",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Rock band",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "GenriX",
            "email": "genrix@aa.io",
            "password": "password",
            "first_name": "Henry",
            "last_name": "Miller",  # Made-up last name
            "display_name": "GenriX",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Electronic music producer",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "SikWorld",
            "email": "sikworld@aa.io",
            "password": "password",
            "first_name": "Spencer",
            "last_name": "Bell",  # Made-up last name
            "display_name": "Sik World",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Musician and songwriter",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "Drake",
            "email": "drake@aa.io",
            "password": "password",
            "first_name": "Aubrey",
            "last_name": "Graham",
            "display_name": "Drake",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Rapper, singer, and songwriter",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "ADayToRemember",
            "email": "adaytoremember@aa.io",
            "password": "password",
            "first_name": "Jeremy",
            "last_name": "McKinnon",  # Made-up last name
            "display_name": "A Day To Remember",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Rock band",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "PostMalone",
            "email": "postmalone@aa.io",
            "password": "password",
            "first_name": "Austin",
            "last_name": "Post",
            "display_name": "Post Malone",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Rapper, singer, and songwriter",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "SorryX",
            "email": "sorryx@aa.io",
            "password": "password",
            "first_name": "Justin",
            "last_name": "Morrow",  # Made-up last name
            "display_name": "Sorry X",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Music producer",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "Seori",
            "email": "seori@aa.io",
            "password": "password",
            "first_name": "Seo",
            "last_name": "Jeong",  # Made-up last name
            "display_name": "Seori",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Singer and songwriter",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "EllaMai",
            "email": "ellamai@aa.io",
            "password": "password",
            "first_name": "Ella",
            "last_name": "Mai",
            "display_name": "Ella Mai",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Singer and songwriter",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
        {
            "username": "Underoath",
            "email": "underoath@aa.io",
            "password": "password",
            "first_name": "Spencer",
            "last_name": "Chamberlain",
            "display_name": "Underoath",
            "profile_image": "https://i1.sndcdn.com/artworks-R5fUpysnmuGuxcMv-5ojqxQ-t500x500.png",
            "profile_bio": "Band",
            "profile_city": random.choice(valid_cities),
            "profile_country": random.choice(valid_countries),
            "profile_background": "",
        },
    ]

    for user_info in user_data:
        user = User(**user_info)
        db.session.add(user)
        db.session.commit()

    # Alternatively, you can commit once after adding all users
    # db.session.commit()



# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_users():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.users RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM users"))

    db.session.commit()
