"""empty message

Revision ID: 18191035b17a
Revises: 
Create Date: 2023-08-11 12:06:44.018019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18191035b17a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsongs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=40), nullable=True),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('profile_bio', sa.String(length=255), nullable=True),
    sa.Column('profile_city', sa.String(length=255), nullable=True),
    sa.Column('profile_country', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=False),
    sa.Column('song_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('preview_imageURL', sa.String(length=255), nullable=True),
    sa.Column('artistId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artistId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    op.drop_table('users')
    op.drop_table('newsongs')
    # ### end Alembic commands ###
